general_settings:
  database_url: os.environ/DATABASE_URL
  master_key: os.environ/LITELLM_MASTER_KEY
model_list:
- litellm_params:
    api_key: os.environ/OPENAI_API_KEY
    model: openai/gpt-4o
  model_name: gpt-4o
