# macOS host config for "macvm" (Apple Silicon, aarch64-darwin) — a UTM guest VM.
#
# Same shared darwin stack as `macos` (modules/darwin/core.nix + the shared
# home.nix profile, Determinate, agenix, home-manager) but with its OWN, leaner
# Homebrew app set and the localhost MCP gateway turned OFF (see below). Think of
# it as the darwin analogue of `nixvm`: a sandbox host, distinct from the real Mac.
#
# SEPARATE PERSONA: this host runs under the `aloshy` / aloshy.ai account (same
# person, isolated local identity), set via the per-host `identity` override at
# the mkDarwin call in flake.nix — so `userName` here resolves to `aloshy`, NOT the
# global `ismailkattakath`.
#
# Activate INSIDE the VM (the guest's login account MUST be `aloshy`, or
# home-manager builds /Users/<wrong> paths):
#   nix run github:kattakath/nix-config#macvm    # first activation (before darwin-rebuild is on PATH)
#   darwin-rebuild switch --flake .#macvm         # thereafter
#
# Grok Build (the xAI `grok` CLI) is NOT a Homebrew app — install it ONCE in the
# VM with xAI's installer, then authenticate:
#   curl -fsSL https://x.ai/cli/install.sh | bash   # installs into ~/.grok (see https://docs.x.ai/build/overview)
#   grok                                             # first run authenticates
# The shared home.nix already puts ~/.grok/bin on PATH, provides Node, and wires
# the grok-build Claude Code plugin — so no Nix app-list entry is needed.
{
  userName,
  lib,
  pkgs,
  ...
}:
let
  # Operator ed25519 public key — sole network login credential (same key as
  # nixpi/nixvm). Safe to commit; imported as a bare string.
  operatorSshKey = import ../secrets/operator-key.nix;
in
{
  imports = [
    ../modules/darwin/core.nix
  ];

  nixpkgs.config.allowUnfree = true;

  # Dock at the BOTTOM on the VM (override core.nix's shared `orientation = "right"`;
  # mkForce because both set the same option). Everything else about the Dock
  # (autohide, tilesize, …) is inherited from core.nix.
  system.defaults.dock.orientation = lib.mkForce "bottom";

  # ---- SSH from the macos host (UTM Shared network) --------------------------
  # Host → guest admin over UTM Shared (bridge100 ≈ 192.168.64.0/24).
  # See docs/macvm-utm-runbook.md and `nix run .#macvm-utm-ssh`.
  #
  # Apple's "Remote Login" (systemsetup / com.openssh.sshd) is unreliable under
  # nix-darwin on this guest — after activation getremotelogin stayed Off and
  # :22 stayed closed. Keep services.openssh for host-key generation +
  # authorized_keys.d wiring, but run **nixpkgs sshd** as our own launchd
  # daemon so SSH does not depend on the Remote Login flag.
  services.openssh = {
    enable = true; # host keys + sshd_config.d fragments
    extraConfig = ''
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      PubkeyAuthentication yes
      PermitRootLogin no
    '';
  };

  # Independent of System Settings → Remote Login. Uses nix-darwin's default
  # Label org.nixos.macvm-sshd and the wait4path wrapper (via `script`).
  launchd.daemons.macvm-sshd = {
    script = ''
      set -euo pipefail
      # Ensure host keys exist (also generated by services.openssh; belt-and-suspenders).
      for t in rsa ecdsa ed25519; do
        f=/etc/ssh/ssh_host_''${t}_key
        if [ ! -s "$f" ]; then
          ${pkgs.openssh}/bin/ssh-keygen -t "$t" -f "$f" -N "" -C ""
        fi
      done
      exec ${pkgs.openssh}/bin/sshd -D -e
    '';
    serviceConfig = {
      KeepAlive = true;
      RunAtLoad = true;
      StandardErrorPath = "/var/log/macvm-sshd.err.log";
      StandardOutPath = "/var/log/macvm-sshd.out.log";
    };
  };

  # MUST be postActivation: extraActivation runs BEFORE launchd plists are
  # installed to /Library/LaunchDaemons, so bootstrap there always no-ops.
  # nix-darwin still uses deprecated `launchctl load` which fails on modern
  # macOS; re-bootstrap with the modern API after the link exists.
  system.activationScripts.postActivation.text = lib.mkAfter ''
    echo "macvm: postActivation — bootstrap org.nixos.macvm-sshd…"
    plist=/Library/LaunchDaemons/org.nixos.macvm-sshd.plist
    /bin/ls -la /Library/LaunchDaemons/org.nixos.macvm* 2>/dev/null || echo "macvm: no org.nixos.macvm* plists yet"
    if [ -e "$plist" ] || [ -L "$plist" ]; then
      /bin/launchctl bootout system/org.nixos.macvm-sshd 2>/dev/null || true
      /bin/launchctl bootout system "$plist" 2>/dev/null || true
      /bin/launchctl unload "$plist" 2>/dev/null || true
      if /bin/launchctl bootstrap system "$plist"; then
        echo "macvm: bootstrap ok"
      else
        echo "macvm: bootstrap failed, trying load -w…"
        /bin/launchctl load -w "$plist" || echo "macvm: load -w also failed" >&2
      fi
      /bin/launchctl enable system/org.nixos.macvm-sshd 2>/dev/null || true
      /bin/launchctl kickstart -k system/org.nixos.macvm-sshd 2>/dev/null || true
      echo "macvm: launchctl print:"
      /bin/launchctl print system/org.nixos.macvm-sshd 2>&1 | /usr/bin/head -20 || true
    else
      echo "macvm: ERROR — $plist missing (launchd.daemons.macvm-sshd not installed)" >&2
    fi
    /usr/bin/sleep 1
    echo "macvm: listeners on :22:"
    /usr/sbin/lsof -iTCP:22 -sTCP:LISTEN 2>/dev/null || echo "(none)"
    # Remote Login flag is cosmetic; may stay Off. Our sshd is org.nixos.macvm-sshd.
    /usr/sbin/systemsetup -f -setremotelogin on 2>/dev/null || true
    /usr/sbin/systemsetup -getremotelogin 2>/dev/null || true
  '';

  # core.nix turns Application Firewall + stealth ON for the real Mac. That
  # blocks host→guest SSH on the UTM Shared bridge — disable on this sandbox.
  networking.applicationFirewall = {
    enable = lib.mkForce false;
    enableStealthMode = lib.mkForce false;
  };

  users.users.${userName} = {
    name = userName;
    home = "/Users/${userName}";
    openssh.authorizedKeys.keys = [ operatorSshKey ];
  };

  # ---- Per-host home-manager tweaks for the VM --------------------------------
  home-manager.users.${userName} = {
    # Trim the MCP gateway (modules/shared/mcp.nix): it spawns ~14 servers at login
    # and one startup failure crashes the whole proxy — heavier than a sandbox VM
    # needs, and several servers depend on apps this host doesn't carry. Disabling
    # the option removes the gateway launchd agent AND the claude-code MCP wiring
    # (config = mkIf cfg.enable). macos keeps it (default = pkgs.stdenv.isDarwin).
    services.mcpGateway.enable = false;

    # Keep the VM visually DISTINCT from the real Mac: opt out of the operator's
    # custom desktop look (modules/shared/desktop-aesthetics.nix) — no custom
    # wallpaper, no Terminal.app "Ubuntu" profile. The VM falls back to the stock
    # macOS wallpaper + default Terminal, so it's recognisable at a glance as the
    # sandbox (even in fullscreen) instead of looking identical to macos.
    local.desktopAesthetics.enable = false;
  };

  # ---- Distinct accent colour = a FULLSCREEN-proof tell -----------------------
  # Wallpaper/Dock/Terminal don't show in a fullscreen app, but the macOS accent +
  # highlight colour tint buttons, selections, checkboxes and menu highlights
  # EVERYWHERE (including inside fullscreen apps). macos leaves it unset (the
  # default multicolour/blue); macvm goes RED so the sandbox is unmistakable at a
  # glance. Set via CustomUserPreferences (untyped keys) into the global domain —
  # AppleAccentColor: -1=graphite 0=red 1=orange 2=yellow 3=green 4=blue 5=purple
  # 6=pink (absent = default). Takes full effect after the next login.
  system.defaults.CustomUserPreferences.NSGlobalDomain = {
    AppleAccentColor = 0; # red
    AppleHighlightColor = "1.000000 0.733333 0.721569 Red";
  };

  # ---- Homebrew apps for THIS host --------------------------------------------
  # The framework (enable/onActivation/taps) lives in modules/darwin/homebrew.nix;
  # this is macvm's leaner set. onActivation.cleanup = "uninstall" removes anything
  # installed but not listed here. No brews, no masApps — GUI apps only.
  homebrew = {
    brews = [ ];
    casks = [
      "opera" # regular Opera (distinct from macos's opera-gx)
      "whatsapp"
      "capcut" # video editor
      "iina" # macOS-native video player (mpv-based) — plays & thumbnails most formats
    ];
    masApps = { };
  };
}
