# Credentialed stdio-MCP launchers on PATH, for the PLUGIN lane.
#
# WHY THIS MODULE EXISTS. The MCP gateway was purged from macOS
# (`local.mcpGateway.enable = false`). Most of its servers had a plugin owner already and
# went home with it; three CREDENTIALED ones did not, and the operator chose to keep the
# capability rather than let it go dark:
#
#   wordpress   site administration over the WP REST API against silvercreek.ai PROD
#   apify       Apify Store Actors — the rag-web-browser / web-fetch scraping lane
#   postgres    the LOCAL pgvector RAG store (NOT a hosted Postgres; the Neon connector
#               covers Neon projects and cannot see 127.0.0.1:5433)
#
# THE SPLIT, identical to `local.gmailMcp`'s and for the same reason:
#   HERE          the launcher binaries, because they read the login Keychain (or a
#                 fleet-internal coordinate) and must not be duplicated into a plugin repo.
#   THE PLUGIN    a `.mcp.json` in github:kattakath/skills naming each launcher by BINARY
#                 NAME, so Claude Code spawns one stdio server per session with no proxy
#                 and nothing shared between clients.
#
# A plugin's `.mcp.json` can set `env` to literals or passthroughs but cannot run
# `security find-generic-password`, which is the whole reason the credential half stays
# in Nix. Secret NAMES live here; no secret VALUE ever reaches the store or argv.
#
# A FOURTH SERVER, FOR A DIFFERENT REASON (2026-10-07). `desktop-commander` needs no
# credential at all — it is here because a plugin's `.mcp.json` equally cannot run
# `sandbox-exec -f <profile>`, and that fence is the only thing making the server safe
# to re-adopt. Same split, same cause: the launcher does what a JSON file cannot. Its
# own entry below carries the why, the risk it does NOT cover, and the measurements.
#
# This is NOT the gateway returning: no long-lived process, no listening socket, no
# tunnel, no portal. Claude Desktop loads no plugins, so none of these four reach it —
# that capability is genuinely gone for Desktop and no declaration here changes it.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.local.pluginMcp;

  inherit (config.home) homeDirectory;

  # ── the desktop-commander fence ───────────────────────────────────────────
  #
  # WHY A FENCE AT ALL, AND WHY AN OS ONE. desktop-commander runs shell commands,
  # which is the capability it is wanted for (below) and also why its own
  # documentation disclaims being a boundary: the README states
  # `allowedDirectories` "currently only restricts filesystem operations, not
  # terminal commands", and SECURITY.md that "directory restrictions are
  # guardrails, not sandboxing". Worse, `set_config_value` lets the MODEL rewrite
  # `allowedDirectories`, so an in-process restriction is one tool call from being
  # lifted by the thing it restricts. Read at the source in dist/, not from a
  # README summary:
  #
  #   tools/filesystem.js:164   `allowedDirectories.length === 0` returns TRUE —
  #                             an EMPTY list means EVERY path is allowed. That is
  #                             also what config-manager.js:84 falls back to on any
  #                             config error, so the in-process check fails OPEN.
  #                             The live pre-Nix config on this Mac was exactly
  #                             that: `"allowedDirectories": []`, telemetry on.
  #   tools/filesystem.js:102   a missing/non-array value makes it WRITE the config
  #                             and fall back to the whole home directory.
  #
  # So the only restriction worth declaring is one the server cannot reach, and on
  # macOS that is Seatbelt. The profile is a STORE PATH — unwritable by
  # construction — and it is handed to the launcher, which execs
  # `sandbox-exec -f` around the interpreter so every forked shell inherits it.
  #
  # SHAPE: permissive base, one restricted axis. `(allow default)` then deny
  # `file-write*` and re-allow a working set, plus an explicit read-deny for the
  # secret paths. Reading the repo IS the job, so reads stay open except for
  # secrets; writes are what must not escape ~/Developer. SBPL is LAST-MATCH-WINS,
  # which is what makes the deny/re-allow/deny-again ordering below work.
  desktopCommanderProfile = pkgs.writeText "desktop-commander.sb" ''
    (version 1)

    ;; Generated by ./plugin-mcp.nix. A fence around a deliberately powerful
    ;; tool, not a least-privilege jail.
    (allow default)

    ;; ---- writes: deny all, then re-allow the working set ------------------
    (deny file-write*)
    (allow file-write*
      ;; The fence. The only durable write target, per the operator's decision.
      (subpath "${homeDirectory}/Developer")
      ;; TMPDIR on macOS is under /private/var/folders; /private/tmp is the
      ;; scratchpad lane. Both are already agent-writable ground.
      (subpath "/private/tmp")
      (subpath "/private/var/folders")
      ;; npx DOWNLOADS the pinned server into the npm cache on first run, so a
      ;; read-only cache means the server never starts at all.
      (subpath "${homeDirectory}/.npm")
      (subpath "${homeDirectory}/.cache")
      ;; So a `nix build`/`nix develop` inside a repo can still reach the daemon.
      (subpath "/nix/var/nix/daemon-socket")
      ;; The device files a shell and node actually write. Enumerated rather than
      ;; `(subpath "/dev")`, which would hand it the raw disks.
      (literal "/dev/null")
      (literal "/dev/zero")
      (literal "/dev/dtracehelper")
      (literal "/dev/ptmx")
      (subpath "/dev/fd")
      (regex #"^/dev/tty")
      (regex #"^/dev/pty"))

    ;; ---- the config must be unwritable FROM INSIDE ------------------------
    ;; This is the rule that neutralises `set_config_value`. The config lives at
    ;; $HOME/.claude-server-commander/config.json (dist/config.js: os.homedir()),
    ;; NOT in the server's working directory. A write there takes a
    ;; proper-lockfile lock, which mkdir's `config.json.lock` IN THIS DIRECTORY,
    ;; then writes a temp file beside it and renames. Denying the DIRECTORY blocks
    ;; the lock, the temp write and the rename alike.
    ;;
    ;; Already covered by the blanket deny above; stated anyway so it survives
    ;; someone widening the allow list, which is exactly how this would rot.
    ;;
    ;; MEASURED 2026-10-07, and this is the one constraint that dictates the
    ;; `home.file` below: Node's recursive `mkdir` SURVIVES on an existing
    ;; write-denied directory but throws EPERM when the directory is ABSENT — and
    ;; utils/trackTools.js:6 does exactly that mkdir at MODULE scope, outside any
    ;; try/catch. An absent config dir therefore kills the server at import. The
    ;; planted config.json is what guarantees the directory exists.
    (deny file-write* (subpath "${homeDirectory}/.claude-server-commander"))

    ;; ---- reads: the secret paths -----------------------------------------
    ;; Rendered from modules/_lib/secret-read-paths.nix — the same data
    ;; ./claude-guardrails.nix renders into its `Read(...)` denies, so the two
    ;; layers cannot drift. Seatbelt resolves symlinks (measured), so the agenix
    ;; path is covered whichever spelling a read uses.
    (deny file-read*
    ${
      lib.concatMapStringsSep "\n" (p: "  (subpath ${builtins.toJSON p})") (
        secretReadPaths.absolute ++ map (p: "${homeDirectory}/${p}") secretReadPaths.underHome
      )
    })
  '';

  secretReadPaths = import ../_lib/secret-read-paths.nix;

  # The config desktop-commander would otherwise write for itself, declared.
  #
  # `welcomeOnboardingEligible` AND `pendingWelcomeOnboarding` are the
  # load-bearing keys, and not for their meaning: config-manager.js:60 mutates the
  # config on startup when `welcomeOnboardingEligible` is undefined. Under the
  # fence that write FAILS, the init try/catch swallows it, and the server falls
  # back to `getDefaultConfig()` — whose `allowedDirectories: []` means
  # UNRESTRICTED (filesystem.js:164). Declaring both keys is what keeps the
  # in-process layer from silently inverting itself on every start.
  #
  # `blockedCommands` is upstream's own default list, kept verbatim per the
  # operator's decision. It is a convenience layer, not the boundary — it matches
  # command names, so it is trivially sidestepped, and the Seatbelt profile is
  # what actually holds.
  desktopCommanderConfig = (pkgs.formats.json { }).generate "desktop-commander-config.json" {
    allowedDirectories = [ "${homeDirectory}/Developer" ];
    telemetryEnabled = false;
    defaultShell = "/bin/zsh";
    fileWriteLineLimit = 50;
    fileReadLineLimit = 1000;
    pendingWelcomeOnboarding = false;
    welcomeOnboardingEligible = false;
    blockedCommands = [
      "mkfs"
      "format"
      "mount"
      "umount"
      "fdisk"
      "dd"
      "parted"
      "diskpart"
      "sudo"
      "su"
      "passwd"
      "adduser"
      "useradd"
      "usermod"
      "groupadd"
      "chsh"
      "visudo"
      "shutdown"
      "reboot"
      "halt"
      "poweroff"
      "init"
      "iptables"
      "firewall"
      "netsh"
      "sfc"
      "bcdedit"
      "reg"
      "net"
      "sc"
      "runas"
      "cipher"
      "takeown"
    ];
  };

  # Per-server shape, read out of the purged `modules/shared/mcp.nix` — its
  # `catalogArgOverrides` (the pins) and `requiredEnvToPasswordCommand` (the Keychain
  # service ids) — rather than from an upstream README. The pins are the measured part:
  # the gateway spawned every server at startup and ONE failing import darked all of
  # them, which is why each `-y <pkg>@<version>` and each `--python` is here.
  servers = {
    # docdyhr/mcp-wordpress, ~59 tools over the WP REST API. `@3.3.30` pins the client
    # library. Three Keychain reads, not one: the SITE URL is stored too, so the live
    # host never appears in a public repo or in this file.
    #
    # VERIFIED LIVE 2026-10-02, because a plugin for a dead endpoint is worse than no
    # plugin: `https://silvercreek.ai/wp-json/` returns 200 with the `wp/v2` namespace
    # present and advertises `application-passwords` auth, and
    # `/wp-json/wp/v2/users/me` returns 401 `rest_not_logged_in` — the route exists and
    # only authentication gates it. Its SIBLING `wordpress-adapter` is a different
    # endpoint and is DEAD: the `mcp` namespace is absent from that same root and
    # `/wp-json/mcp/mcp-adapter-default-server` 404s `rest_no_route` (the failure that
    # darked all 25 gateway servers, removed in #725). The adapter is deliberately NOT
    # given a home here.
    wordpress = {
      interpreter = "npx";
      args = [
        "-y"
        "mcp-wordpress@3.3.30"
      ];
      keychainEnv = {
        WORDPRESS_SITE_URL = "mcp:silvercreek.ai:wp_url";
        WORDPRESS_USERNAME = "mcp:silvercreek.ai:wp_user";
        WORDPRESS_APP_PASSWORD = "mcp:silvercreek.ai:wp_app_password";
      };
    };

    # apify/actors-mcp-server run LOCALLY against APIFY_TOKEN — NOT the hosted
    # mcp.apify.com OAuth bridge used until 2026-08-19, whose interactive browser
    # redirect a spawned stdio server cannot complete any more than a launchd agent could.
    apify = {
      interpreter = "npx";
      args = [
        "-y"
        "@apify/actors-mcp-server"
      ];
      keychainEnv.APIFY_TOKEN = "mcp:apify.com:token";
    };

    # crystaldba's postgres-mcp ("Postgres MCP Pro") — a general SQL executor, so every
    # pgvector operation is just SQL it can run. The official
    # @modelcontextprotocol/server-postgres is ARCHIVED with an unpatched
    # read-only-bypass SQL-injection CVE and is deliberately avoided.
    #
    # The ONLY one of the three with no secret: `databaseUri` is loopback `trust` auth
    # with no password, so it is a plain env value rather than a Keychain read — and it
    # comes from the local-rag capsule's own option, so the port/role/db are stated once.
    # `--access-mode=unrestricted` lets it create tables and insert vectors; the blast
    # radius is bounded by the role, which owns ONLY that one database.
    #
    # The two pins are the measured ones: `--python 3.12` steers uv away from a CPython
    # whose wheels pglast's deps lag, and `--with mcp<2 --from postgres-mcp==0.3.0` pins
    # around mcp 2.0 removing the vendored `fastmcp` that 0.3.0 still imports.
    #
    # VERIFIED RUNNING 2026-10-02 before declaring it: postgres is listening on
    # 127.0.0.1:5433 and `postgresql://mcp@127.0.0.1:5433/ragdb` connects with the
    # `vector` extension at 0.8.5.
    postgres = {
      interpreter = "uvx";
      args = [
        "--python"
        "3.12"
        "--with"
        "mcp<2"
        "--from"
        "postgres-mcp==0.3.0"
        "postgres-mcp"
        "--access-mode=unrestricted"
      ];
      plainEnv.DATABASE_URI = config.local.rag.pgvector.databaseUri;
    };

    # wonderwhy-er/DesktopCommanderMCP — shell + filesystem, fenced by Seatbelt.
    #
    # WHY IT IS BACK, having gone with the gateway. It is the escape hatch for one
    # specific dead end: a worktree-isolated Claude Code session whose worktree has
    # been DELETED refuses every Bash call ("This session is isolated in the
    # worktree … Refusing to run it there"), and spawned agents inherit the lock.
    # desktop-commander runs commands outside the Bash tool, so the guard never
    # sees them and the session can dig itself out.
    #
    # THAT IS ALSO ITS RISK, STATED PLAINLY. Routing around the Bash tool routes
    # around every Bash rule in ./claude-guardrails.nix, not just the worktree
    # guard: `secret reveal`, `security find-generic-password -w`, `agenix -d`,
    # `git push --force` and `gh pr merge` are all Bash-TEXT denies with no
    # filesystem component, so Seatbelt cannot reproduce them and does not. The
    # fence covers the FILE axis only — writes outside ~/Developer and reads of the
    # secret PATHS. Keychain reads in particular go through securityd over mach
    # IPC, so a file deny would not stop them even in principle, and the operator's
    # test plan deliberately requires them to keep working (git/gh need them).
    # The operator accepted that gap on 2026-10-07 rather than gate the exec tools
    # behind a PreToolUse matcher; this comment is the record, not a to-do.
    #
    # `@0.2.52` is the current stable, read off the registry 2026-10-07 (published
    # 2026-09-29; `0.3.1-alpha.0` carries the `alpha` tag and is deliberately not
    # taken). Pinned for the same reason as every other entry here: an unpinned
    # `-y` resolves to whatever is newest at first spawn.
    #
    # No Keychain entry and no `plainEnv`: it needs no credential of its own. The
    # whole configuration is the `sandboxProfile` plus the planted config.json.
    desktop-commander = {
      interpreter = "npx";
      args = [
        "-y"
        "@wonderwhy-er/desktop-commander@0.2.52"
      ];
      sandboxProfile = desktopCommanderProfile;
    };
  };
in
{
  options.local.pluginMcp.servers = lib.mkOption {
    type = lib.types.listOf (lib.types.enum (lib.attrNames servers));
    default = [ ];
    example = [ "postgres" ];
    description = ''
      Which credentialed MCP launchers to put on PATH, one binary each, named
      `nix-mcp-<name>`. An enum rather than free strings, so a typo fails here instead of
      shipping a plugin that names a binary nobody builds.

      Each one is claimed by a plugin in github:kattakath/skills that declares a server
      whose `command` is that binary name. Enabling a name here without the plugin
      installed just leaves an unused binary on PATH; installing the plugin without the
      name here leaves a server that cannot start.

      Empty by default and set PER HOST: which third-party accounts the operator holds is
      identity, not fleet shape — a template consumer wants the mechanism without
      inheriting someone else's WordPress site or Apify billing.

      Credentials come from the login Keychain at launch (`wordpress`, `apify`), so no
      secret is in the store or in this list. `postgres` needs none — its URI is
      loopback `trust` — and neither does `desktop-commander`, which is here for its
      Seatbelt fence rather than for a credential.
    '';
  };

  # Darwin-gated: the launchers read the macOS login Keychain via /usr/bin/security, and
  # the pgvector store is a darwin-only launchd agent. On Linux the option exists and does
  # nothing, which keeps hosts/*.nix free of platform conditionals.
  config = lib.mkIf (cfg.servers != [ ] && pkgs.stdenv.hostPlatform.isDarwin) {
    # Declaring the postgres server while its database is switched off would ship a server
    # that cannot connect — the exact "plugin for a dead endpoint" failure this module's
    # header warns about, so it fails at eval instead of at first tool call.
    assertions = [
      {
        assertion = !(builtins.elem "postgres" cfg.servers) || config.local.rag.pgvector.enable;
        message = "local.pluginMcp.servers includes \"postgres\", but local.rag.pgvector.enable is false — the launcher would point DATABASE_URI at a store that is not running.";
      }
      # A fence rendered from an empty path list is a profile that denies no read
      # at all — well-formed, and silently not a floor. Same objection
      # ./claude-guardrails.nix raises about its own twin, same answer: fail here.
      {
        assertion =
          !(builtins.elem "desktop-commander" cfg.servers)
          || (secretReadPaths.absolute != [ ] && secretReadPaths.underHome != [ ]);
        message = "modules/_lib/secret-read-paths.nix yielded an empty path list — the desktop-commander Seatbelt profile would deny no secret read.";
      }
    ];

    # The config dir MUST exist before the server starts, and its contents must be
    # declared. Both halves are this one `home.file`:
    #
    #   EXISTENCE — utils/trackTools.js:6 runs `mkdir(dir, {recursive:true})` at
    #     module scope with no try/catch. Measured 2026-10-07: that call survives
    #     when the directory exists and is write-denied, but throws EPERM when the
    #     directory is ABSENT. Absent dir => the server dies at import. Planting a
    #     file inside it is what guarantees existence.
    #   CONTENT — see `desktopCommanderConfig` above for why the onboarding keys
    #     are load-bearing rather than cosmetic.
    #
    # `force = true` is deliberate and needed. UPSTREAM FIRST: `home.file.<n>.force`
    # is a real option in the PINNED home-manager (f53f326,
    # modules/lib/file-type.nix:135), documented as unconditionally replacing the
    # target and "silently delete[ing] the target regardless of whether it is a file
    # or link". Without it activation ABORTS here, because this Mac already carries
    # a REAL config.json at that path — desktop-commander ran outside Nix until the
    # 2026-10-01 purge (1,565 bytes, last written 2026-10-05, 705 tool calls of
    # `usageStats` and a telemetry `clientId`). Nothing in it is worth preserving:
    # the counters cannot accrue once the directory is write-denied, and dropping
    # the `clientId` is the point of `telemetryEnabled = false`.
    home.file.".claude-server-commander/config.json" =
      lib.mkIf (builtins.elem "desktop-commander" cfg.servers)
        {
          source = desktopCommanderConfig;
          force = true;
        };

    home.packages = map (
      name:
      pkgs.callPackage ../../packages/keychain-mcp.nix { } (
        servers.${name}
        // {
          inherit name;
          inherit (config.home) homeDirectory;
        }
      )
    ) cfg.servers;
  };
}
