# agenix rules — declares each committed .age secret and who may decrypt it.
# Consumed ONLY by the `agenix` CLI (agenix -e/-r), never imported into a system
# config. Each secret is encrypted to its target HOST's SSH host key (so the host
# decrypts at activation with /etc/ssh/ssh_host_ed25519_key) plus the OPERATOR's
# key (so secrets stay editable). Recipients are SSH public keys directly —
# agenix uses age's SSH support, so there is no ssh-to-age step.
#
# Edit a secret:   nix run github:ryantm/agenix -- -e secrets/<name>.age
# Re-key after changing recipients:  … -- -r
let
  # operator (ismail) — ~/.ssh/id_ed25519.pub; backed up off-machine, kept editable.
  operator = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAq9VALx6Y6OERWlWWvudcTUEO29BMFl3bbGwoVSTGsS";
  # nixpi host key (/etc/ssh/ssh_host_ed25519_key.pub) — regenerated by the 2026-07-08 SD reflash.
  nixpi = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIApnN4kP6/o3RRZTN1iJKq9lLdMFuhvcxKwxDjvL9Anh";
  # macos host key (/etc/ssh/ssh_host_ed25519_key.pub).
  macos = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBVj8AMmTJYHMe8zJCfvTEHEog8E+FEiE5Fob3uhwiau";
  # nixvm host key (/etc/ssh/ssh_host_ed25519_key.pub) — via ssh-keyscan 2026-07-08.
  nixvm = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHYPpSbmVt442jdPPCix1D9wuUhVgt2qhUXloDOntPSy";
in
{
  # nixpi's Cloudflare Tunnel connector token (EnvironmentFile: TUNNEL_TOKEN=…).
  "cloudflared-token.age".publicKeys = [
    operator
    nixpi
  ];
  # macos self-hosted GitHub Actions runner PAT.
  "gh-runner-token.age".publicKeys = [
    operator
    macos
  ];
  # nixvm self-hosted GitHub Actions runner PAT (github-nix-ci).
  "gh-runner-token-nixvm.age".publicKeys = [
    operator
    nixvm
  ];
}
